---

  - name: Copy-files
    hosts: linux_nodes
    become: true

    vars:
      user: "Linus Torvalds"
    

    tasks:
      
      - name: Copy Redhat filess
        copy:
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
        loop:
          - { src: 'redhat-files/rfile1.txt', dest: '/etch/myfolder/'}
          - { src: 'redhat-files/rfile2.txt', dest: '/etch/myfolder/'}
        notify: 
          - RedHat files copied
        when: ansible_os_family == 'RedHat'

      
      - name: Copy Debian files
        copy:
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
        loop:
          - { src: 'debian-files/dfile1.txt', dest: '/etch/myfolder/'}
          - { src: 'debian-files/dfile2.txt', dest: '/etch/myfolder/'}
        notify:
          - Debian files copied
        when: ansible_os_family == 'Debian'

    handlers:
      - name: RedHat files copied
        blockinfile:
          path: /etc/ansible/redhat_log.txt
          marker: ""
          insertafter: EOF
          block: |
            Files were copied last time at {{ ansible_date_time.iso8601 }} from user {{ user }}

      - name: Debian files copied
        blockinfile:
          path: /etc/ansible/debian_log.txt
          marker: ""
          insertafter: EOF
          block: |
            Files were copied last time at {{ ansible_date_time.iso8601 }} from user {{ user }}